### ISSUE TITLE
docker image doesn't run

### ISSUE THREAD

**Issue by hamsterksu** [monitoringartist/zabbix-docker-monitoring#38]
Hi 

i try to use your docker image `monitoringartist/zabbix-agent-xxl-limited:latest ` 
but it crashes with error 

```
Zocker XXL v0.9.1b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com
Freeware licence - Usage of this binary is restricted to oficial monitoringartist Docker images only.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4e77d7]

goroutine 1 [running]:
github.com/fsouza/go-dockerclient.(*Env).Map(0x0, 0x1b)
        /usr/lib/golang/src/github.com/fsouza/go-dockerclient/env.go:159 +0x27
github.com/fsouza/go-dockerclient.(*Env).Get(0x0, 0x7e07e0, 0x4, 0x0, 0x0)
        /usr/lib/golang/src/github.com/fsouza/go-dockerclient/env.go:20 +0x2f
main.main()
        /root/zabbix-agent-docker-commercial/zocker-xxl.go:50 +0xc27

goroutine 22 [select]:
net/http.(*persistConn).readLoop(0xc8200ca160)
        /usr/lib/golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:685 +0xc78

goroutine 23 [select]:
net/http.(*persistConn).writeLoop(0xc8200ca160)
        /usr/lib/golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/golang/src/net/http/transport.go:686 +0xc9d
```

**Comment by jangaraj** [comment]
Please open issue in https://github.com/monitoringartist/zabbix-agent-xxl. This is not right project. 
Please provide more details there: 
- how did you start docker container
- what is your host OS, docker version, ...
