### ISSUE TITLE
Can't run zabbix agent

### ISSUE THREAD

**Issue by golak** [monitoringartist/zabbix-docker-monitoring#53]
``` 
cat /etc/issue
Ubuntu 15.10

docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

ls /var/run
acpid.socket   containerd    dbus         initctl         lightdm      mlocate.daily.lock  netns           pppconfig     samba            sshd.pid         teamviewerd.pid  user
agetty.reload  crond.pid     docker       initramfs       lightdm.pid  motd.dynamic        network         resolvconf    sendsigs.omit.d  sudo             thermald         utmp
avahi-daemon   crond.reboot  docker.pid   irqbalance.pid  lock         mount               NetworkManager  rsyslogd.pid  shm              systemd          tmpfiles.d       uuidd
cgmanager      cups          docker.sock  kerneloops.pid  log          mysqld              plymouth        runc          sshd             teamviewerd.ipc  udev
```
Run container
```
root@:~# docker run  --name=zabbix-agent-xxl \
 -h $(hostname) \
 -p 10050:10050  \
-v /:/rootfs \
 -e "ZA_Server=zabbix.srv" \
 -e "ZA_ServerActive=zabbix.srv" \
 -e "ZA_StartAgents=10" \
 -e "ZA_Timeout=30" \
-it --rm \
--privileged \
monitoringartist/zabbix-agent-xxl-limited:latest

Zocker XXL v0.9.4b public limited version
Copyright (C) 2014-2016 Jan Garaj - www.monitoringartist.com 
Freeware licence - Usage of this binary is restricted to official monitoringartist Docker images only.
Starting Zabbix Agent [sciencepulse.vitech.com.ua]. Zabbix 3.0.4 XXL (2016-08-21) (revision 61185).
Press Ctrl+C to exit.

    11:20160914:102452.722 Starting Zabbix Agent [sciencepulse.vitech.com.ua]. Zabbix 3.0.4 XXL (2016-08-21) (revision 61185).
    11:20160914:102452.722 **** Enabled features ****
    11:20160914:102452.722 IPv6 support:          YES
    11:20160914:102452.722 TLS support:           YES
    11:20160914:102452.722 **************************
    11:20160914:102452.722 using configuration file: /etc/zabbix/zabbix_agentd.conf
    11:20160914:102452.723 Cannot connect to standard docker's socket /var/run/docker.sock
    11:20160914:102452.723 loaded modules: zabbix_module_docker.so, zabbix_module_stress.so
    11:20160914:102452.724 agent #0 started [main process]
    12:20160914:102452.724 agent #1 started [collector]
    13:20160914:102452.724 agent #2 started [listener #1]
    14:20160914:102452.725 agent #3 started [listener #2]
    18:20160914:102452.725 agent #7 started [listener #6]
    19:20160914:102452.726 agent #8 started [listener #7]
    21:20160914:102452.726 agent #10 started [listener #9]
    15:20160914:102452.728 agent #4 started [listener #3]
    23:20160914:102452.728 agent #12 started [active checks #1]
    17:20160914:102452.728 agent #6 started [listener #5]
    20:20160914:102452.729 agent #9 started [listener #8]
    16:20160914:102452.730 agent #5 started [listener #4]
    22:20160914:102452.732 agent #11 started [listener #10]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40596a]

goroutine 1 [running]:
panic(0x7eb920, 0xc82000a090)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
main.main()
	/root/git/zabbix-agent-xxl-source-code-private/zabbix-agent-3.0-limited/zocker-xxl.go:191 +0x496a

```

**Comment by jangaraj** [comment]
Try to add `-v /var/run:/var/run` volume.

**Comment by golak** [comment]
Thank you! I forgot this option for Ubuntu.
